### ISSUE TITLE
LoRa-Gateway-OS Full produces incomplete packet-forwarder global_conf.json for US915

### ISSUE THREAD

**Issue by DavidAMills** [brocaar/chirpstack-gateway-os#16]
The global_conf.json file produced has no table lookups for US915. I'm using a RAK831 Pilot Gateway, and I selected the RAK831 Development Kit for the Concentrator.

**Comment by brocaar** [comment]
I have been following the config examples provided by: https://github.com/Lora-net/packet_forwarder/tree/master/lora_pkt_fwd/cfg

Would you like to create a pull-request to add these missing `tx_lut_` values?

**Comment by brocaar** [comment]
Closing this issue as this part of the configuration has been updated with the migration to the concentratord daemon.
