### ISSUE TITLE
Support for Raspberry pi 4

### ISSUE THREAD

**Issue by velegip** [brocaar/chirpstack-gateway-os#17]
Hi!

The current version is 3.0.0-test2 is support up to pi3.
Can you modify the image for the new raspberry pi 4?

Thank you!

**Comment by brocaar** [comment]
Unfortunately this is not (yet) possible as the Thud version of the meta-raspberrypi layer does not provide this machine (yet?): http://git.yoctoproject.org/cgit/cgit.cgi/meta-raspberrypi/tree/conf/machine?h=thud.

It is available in the Warrior version, but this would require to update the other layers: http://git.yoctoproject.org/cgit/cgit.cgi/meta-raspberrypi/tree/conf/machine?h=warrior.

**Comment by velegip** [comment]
I see. Thank you.

Then I'll wait for it.

**Comment by hotmonitor** [comment]
Hello 
 I test IMG chirpstack-gateway-os-full-raspberrypi3--20191102145611.sdimg in Raspberry Pi4 Buster but img not work. Do you plan to put Pi4 img version and when? Thanks

**Comment by brocaar** [comment]
Yes I do plan to add support for the Pi 4. I just received one for testing.

**Comment by brocaar** [comment]
Please see #45
