### ISSUE TITLE
drogon.net wiringpi repo is down 

### ISSUE THREAD

**Issue by joeysmart** [brocaar/chirpstack-gateway-os#20]
wiringpi_git.bb submodule should be updated

**Comment by andershedberg** [comment]
Just so I can remember this for myself - change line 14 of file lora-gateway-os/layers/bsp/meta-raspberrypi/recipes-devtools/wiringpi/wiringpi_git.bb to point to a mirror. Like this:
 
`
SRC_URI = "git://github.com/WiringPi/WiringPi.git\
`

**Comment by brocaar** [comment]
Actually, after some testing I'm not sure if this is a real dependency :blush: I'm working on a new release and I have removed it as a dependency and all works fine. I might have based my list of dependencies on a  base-image and never looked back at this list....

**Comment by brocaar** [comment]
This has already been solved in the master branch :)
