### ISSUE TITLE
AS923 missing for RAK831

### ISSUE THREAD

**Issue by jeremyherbert** [brocaar/chirpstack-gateway-os#21]
I have a RAK831 and I have used it on TTN with AS923. However, when I run `gateway-config` AS923 is not one of the options available.

Image version is `lora-gateway-os-full-raspberrypi3--20190810092349.sdimg`

**Comment by brocaar** [comment]
If you would like to contribute, adding AS923 configuration would be much appreciated :-)

Please see:
https://github.com/brocaar/lora-gateway-os/tree/master/layers/targets/meta-raspberrypi/recipes-lora/lora-packet-forwarder

And:
https://github.com/brocaar/lora-gateway-os/blob/master/layers/targets/meta-raspberrypi/recipes-core/gateway-config/gateway-config/gateway-config.sh

**Comment by jeremyherbert** [comment]
I tried to do that, but #22 blocked me ;)

**Comment by tonysmith55** [comment]
Hi Orne,  I created AS923-1 and AS923-2 when the original AU and US frequency blocks were developed.  I'm not confident with git but the files can be found at https://github.com/tonysmith55/lora-gateway-additions  
You will also see files for the other countries currently not included (eg India, Korea, China etc etc)

**Comment by brocaar** [comment]
This has been implemented by #41
