### ISSUE TITLE
About lora-gtaeway-os running hardware

### ISSUE THREAD

**Issue by sadyqd** [brocaar/chirpstack-gateway-os#24]
How to run on other hardware except Raspberry Pi 3 and LORIX One?What do I need to do? What are  requirements about the hardware?
                                                        thanks
                                                                sandy

**Comment by brocaar** [comment]
You need to implement a bsp (`layers/bsp/...`) and target layer (`layers/targets/...`). You can read more about how Yocto works (and how to implement bsp layers) at: https://www.yoctoproject.org/.
