### ISSUE TITLE
gateway-os-base image missing /opt directory

### ISSUE THREAD

**Issue by mrbubble62** [brocaar/chirpstack-gateway-os#38]
It looks like there should be gateway-utils installed to /opt/libloragw-sx1301/gateway-utils/
However /opt directory is not in the gateway-os-base image

**Comment by brocaar** [comment]
Only if the `-utils` package is part of the ChirpStack Gateway OS images, which is not the case. You can include this package in the `chirpstack-gateway-os-base` and / or `-full` image if you want to use these tools, but you need build your own image.

(https://github.com/brocaar/chirpstack-gateway-os/blob/master/layers/chirpstack/meta-semtech/recipes-lora/libloragw-sx1301/libloragw-sx1301_5.0.1.bb#L50)

**Comment by mrbubble62** [comment]
Sorry I am new to bitbake, should I add this to chirpstack-gateway-os/meta/recipes-core/images/chirpstack-gateway-os-base.bb?

>  IMAGE_INSTALL += " \\
>    gateway-utils \\
>   packagegroup-base \\
>   ...
