### ISSUE TITLE
Applications / testapp / Integrations / HTTP results in empty POST Messages

### ISSUE THREAD

**Issue by joau-mms** [brocaar/chirpstack-gateway-os#40]
HTTP Post seems to be empty.
Config:
![image](https://user-images.githubusercontent.com/59052421/75165057-0f92b980-5722-11ea-9024-17b7ab506876.png)

Target of HTTP Post is an Apache2 with PHP
```
if (isset($_POST)) {
    $text = var_export($_POST, true) . "\n\n";
    file_put_contents("dumb.txt", " " . $text, FILE_APPEND);
    echo print_r($_POST, true);
}
```

Result is dumb.txt containing an empty array:
```
 array (
)
```

**Expected Behavior**

Getting a POST with some data, preferable some json ;)

**Comment by brocaar** [comment]
I don't know your application / setup, but please try to reproduce this with for example https://postb.in/.

**Comment by joau-mms** [comment]
Well Thanks!
It was my implementation, is seems, that PHPs $_Post won't fetch json.
