### ISSUE TITLE
Using ChirpStack layer on other Yocto Image

### ISSUE THREAD

**Issue by kbm15** [brocaar/chirpstack-gateway-os#48]
I've been trying to port ChirpStack into the example yocto image for Simatic IOT2000.  
What I've done is:  
Copy the following folders from layers to my building path  
chirpstack-gateway-os/layers/meta-clang  
chirpstack-gateway-os/layers/meta-rust-bin   
chirpstack-gateway-os/layers/chirpstack   
  
Add them to bblayers.conf   
Add the corresponding packets to IMAGE_INSTALL_APPEND

Then while bitbakin i got these errors:
chirpstack-gateway-bridge-3.7.1-r1 do_package: QA Issue: File '/usr/bin/chirpstack-gateway-bridge' from chirpstack-gateway-bridge was already stripped, this will prevent future debugging! [already-stripped]

For every packet from chirpstack. No problem with other utilities.
Can I get some help?

**Comment by brocaar** [comment]
> chirpstack-gateway-bridge-3.7.1-r1 do_package: QA Issue: File '/usr/bin/chirpstack-gateway-bridge' from chirpstack-gateway-bridge was already stripped, this will prevent future debugging! [already-stripped]

That is expected. The recipe is pulling the pre-compiled ARM binaries, which are already optimized for distribution.

Unfortunately there is no Yocto / OpenEmbedded class for Go yet, which is compatible with Go modules. That is why I decided to just pull the pre-compiled binaries.
