### ISSUE TITLE
wifi won't connect if ethernet connection is present

### ISSUE THREAD

**Issue by gom-dot-sh** [brocaar/chirpstack-gateway-os#49]
tested version: Self compiled with sources from 04.04.2020

problem: If wifi is configured and the system boots while an ethernet connection is present, the ChirpstackOS won't connect to wifi.
The system booted without ethernet is going to connect to wifi and can be connected to ethernet after boot up. In this case booth connections are operational.

expected behaviour: Starting the system with connected ethernet and configured wifi should lead to two working network connections after boot.

Additionally: Using sudo gateway-config for wifi configuration always reboots the system. That should not be necessary.

**Comment by brocaar** [comment]
This is a "feature" from connman. You can override this:

```
       AlwaysConnectedTechnologies=technology[,...]
              List of technoolgies which are always connected regardless of PreferredTechnologies
              setting  (AutoConnect  =  true).  The  default  value  is empty and this feature is
              disabled unless explicitly enabled in the config file.
```

http://manpages.ubuntu.com/manpages/cosmic/man5/connman.conf.5.html

> Additionally: Using sudo gateway-config for wifi configuration always reboots the system. That should not be necessary.

Without a reboot, I was unable to change from AP mode to connect it to an AP. I agree for most cases this is not needed, but when you are in AP mode and have no other option to connect to the Ri (e.g. Zero W), then this is the safest option.
