### ISSUE TITLE
Using systemd

### ISSUE THREAD

**Issue by evandavey** [brocaar/chirpstack-gateway-os#58]
Hi,
How can I use systemd?
I added the following to local.conf but get a yocto circular dependecy when building (due the the rootfs overlay)

```
# Enable systemd
DISTRO_FEATURES_append = " systemd "
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
```

**Comment by brocaar** [comment]
I don't know. Currently I have no plans to support systemd.
