### ISSUE TITLE
Add chirpstack-udp-bridge support

### ISSUE THREAD

**Issue by fernandobarreto** [brocaar/chirpstack-gateway-os#68]
Hi!!
Suggestion: the next Chirpstack-gateway-os release should support the chirpstack-udp-bridge feature (https://github.com/brocaar/chirpstack-udp-bridge) in order to have a gateway with multiple simultaneous packet-forwarder instances for different network servers (example: Chirpstack server and TTN server).

**Comment by brocaar** [comment]
You might have missed this commit ;) https://github.com/brocaar/chirpstack-gateway-os/commit/54fda917aa41bc09d29322aa9d6f14b6f8e1f127

**Comment by fernandobarreto** [comment]
Sorry about that, I've just checked the gateway-os date release (2020-Sep-11).
