### ISSUE TITLE
rpi 1 black screen on boot

### ISSUE THREAD

**Issue by piechade** [brocaar/chirpstack-gateway-os#69]
Last v3.3.2 release is not booting on pi 1 and screen is black after bootloader.

Steps:

1. Flash image
2. start pi

| Component             | Version |
| ----------------------| ------- |
| ChirpStack Gateway OS | v3.3.2  |

**Comment by brocaar** [comment]
I have tested the just released v3.3.3 on a RPi 1 without any issues. Could you test with this version as well?

**Comment by piechade** [comment]
Sorry my information were misleading. I tried it on commit https://github.com/brocaar/chirpstack-gateway-os/commit/552602852063af8230e1fbc0911a316e8abc860a. So I actually tried it on 3.3.3.

**Comment by piechade** [comment]
Sorry I forgot to uncomment one line of my custom code.
