### ISSUE TITLE
IN865 on Gateway OS base

### ISSUE THREAD

**Issue by saiprakash1407** [brocaar/chirpstack-gateway-os#74]
Gateway OS base image does not contains IN865 for RAK2245,
is there any other method through which i can configure it?

**Comment by manivalaguru** [comment]
have to got it working in IN865? i am also doing the same thing

**Comment by saiprakash1407** [comment]
> have to got it working in IN865? 

NO

**Comment by manivalaguru** [comment]
okay, i have done that

**Comment by saiprakash1407** [comment]
> okay, i have done that

Can please tell me what changes we need to do.

**Comment by manivalaguru** [comment]
no bro i have used lora packet forwarder chirpstack bridge in my gateway and application and netwrk server sepretely

**Comment by saiprakash1407** [comment]
your not using chirpstack gateway os base.?

> no bro i have used lora packet forwarder chirpstack bridge in my gateway and application and netwrk server sepretely
you are  not using chirpstack gateway os base.?

**Comment by manivalaguru** [comment]
no using only chirpstack servers and bridge

**Comment by brocaar** [comment]
This has been added in https://github.com/brocaar/chirpstack-gateway-os/commit/82e46e6b1897cdd71f577c61990630ce7633f0cf.
