### ISSUE TITLE
issue changing channel configuration to 865 in chripstack os with ic880a gateway

### ISSUE THREAD

**Issue by manivalaguru** [brocaar/chirpstack-gateway-os#76]
hello,
i am using ic880a with chripstack full os and raspberry pi by default my channel configuration is 868 i want to change it to 865 i have done changes in chirpstack concentratord config ->channel according to indian region and  in genral configuration under model="imst_ic880a_in865" but that does not working can you please tell me what should i do to cahnge the config to IN865
thanks and regards
manikandan v

**Comment by saiprakash1407** [comment]
Hi manikandan,

I am also facing the same problem. did you get the any solution for this?

**Comment by iyer3142** [comment]
I looked at all the files in /opt, /etc folders and changed files for EU868 to match the frequencies in India. I got my node communicating with the gateway sucessfully. I would recommend that you do the same :)

**Comment by brocaar** [comment]
This has been implemented in the above commit + https://github.com/brocaar/chirpstack-gateway-os/commit/82e46e6b1897cdd71f577c61990630ce7633f0cf.

**Comment by iyer3142** [comment]
Can you confirm if the IN865 has been implemented for SX1301 & 1302 too?

**Comment by brocaar** [comment]
I focused on this issue, which was IN865 for the iC880a concentrator shield (SX1301 chipset). Please open an other issue or pull-request for different questions :)
