### ISSUE TITLE
splitout meta/receipe into own repo

### ISSUE THREAD

**Issue by toepi** [brocaar/chirpstack-gateway-os#80]
thanks for making this great product.

## Summary

it would be nice if it possible to use your recipe in another build. so why not move all chripstack related recipes into it own repo and than use a submodule her.

## What is the use-case?

build a own yocto image with ChirpStack components.

## Can you implement this by yourself and make a pull request?

if this feature is wanted and the repository which should contains the recipes - for sure.

**Comment by dougreese** [comment]
I have the same situation, and ended up integrating the Chirpstack recipes using a sparse checkout submodule.  Here is an example: https://github.com/dougreese/rpi-chirpstack-sparse

I am only including in my image:
* chirpstack-gateway-bridge
* chirpstack-concentratord

But additional recipes could be added, especially if creating a defined custom image.

However, I am currently having a problem using the [Yocto 3.4 (honister)](http://docs.yoctoproject.org/migration-guides/migration-3.4.html) release: the recipes using Rust fail.  Details are in pull request https://github.com/brocaar/chirpstack-gateway-os/pull/83.  The hardknott release should work.
